### ISSUE TITLE
shouldn't be  in css

### ISSUE THREAD

**Issue by OzodaKhamdamova** [asrorbek07/Zendit#1]
https://github.com/asrorbek07/Zendit/blob/0387d958dfc82733e6c957643fd2ece2e8b0b767/css/styles.css#L261
"Special Offer" must be placed in html as it means a lot) in your case the content isn't read and outcomes some issues

**Comment by asrorbek07** [comment]
> https://github.com/asrorbek07/Zendit/blob/0387d958dfc82733e6c957643fd2ece2e8b0b767/css/styles.css#L261
> 
> 
> "Special Offer" must be placed in html as it means a lot) in your case the content isn't read and outcomes some issues

changed
